=== conradohillar/TP2doParcialXML/data/season_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="season_data" type="resultT"/>
 <xsd:complexType name="resultT">
   <xsd:choice>
       <xsd:sequence>
           <xsd:element name="season" type="seasonT"/>
           <xsd:element name="stages">
               <xsd:complexType>
                   <xsd:sequence>
                       <xsd:element name="stage" type="stageT" minOccurs="1" maxOccurs="unbounded" />
                   </xsd:sequence>
              </xsd:complexType>
           </xsd:element>
           <xsd:element name="competitors">
               <xsd:complexType>
                   <xsd:sequence>
                       <xsd:element name="competitor" type="competitorT" minOccurs="0" maxOccurs="unbounded" />
                   </xsd:sequence>
              </xsd:complexType>
           </xsd:element>
       </xsd:sequence>
       <xsd:element name="error" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
   </xsd:choice>
 </xsd:complexType>

 <xsd:complexType name="seasonT">
   <xsd:sequence>
 		<xsd:element name="name" type="xsd:string"/>
        <xsd:element name="competition">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"/>
                    <xsd:element name="gender" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
        <xsd:element name="date">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="start" type="xsd:string"/>
                    <xsd:element name="end" type="xsd:string"/>
                    <xsd:element name="year" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
 	</xsd:sequence>
</xsd:complexType>

 <xsd:complexType name="stageT">
  <xsd:sequence>
    <xsd:element name="groups">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="group" type="groupT" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
  </xsd:sequence>
  <xsd:attribute name="phase" type="xsd:string"/>
  <xsd:attribute name="start_date" type="xsd:string"/>
  <xsd:attribute name="end_date" type="xsd:string"/>
 </xsd:complexType>

 <xsd:complexType name="groupT">
  <xsd:sequence>
    <xsd:element name="competitor" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="abbreviation" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
  </xsd:sequence>
 </xsd:complexType>
 <xsd:complexType name="scoreT">
  <xsd:sequence>
    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="score" type="xsd:string"/>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="competitorT">
  <xsd:sequence>
    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="players">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="player" minOccurs="0" maxOccurs="unbounded" type="playerT"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
  </xsd:sequence>
  <xsd:attribute name="id" type="xsd:string"/>
 </xsd:complexType>

 <xsd:complexType name="playerT">
  <xsd:sequence>
    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="type" type="xsd:string"/>
    <xsd:element name="date_of_birth" type="xsd:string"/>
    <xsd:element name="nationality" type="xsd:string"/>
    <xsd:element name="events_played" type="xsd:int"/>
  </xsd:sequence>
  <xsd:attribute name="id" type="xsd:string"/>
 </xsd:complexType>
</xsd:schema>

=== conradohillar/TP2doParcialXML/season_dataaa.xml
<?xml version="1.0" encoding="UTF-8"?><season_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./data/season_data.xsd"><season><name>Super League 2008</name><competition><name>Super League</name><gender>men</gender></competition><date><start>2008-02-01</start><end>2008-10-06</end><year>2008</year></date></season><stages><stage start_date="2008-02-01" end_date="2008-09-09" phase="stage_1"><groups><group><competitor id="sr:competitor:4275"><name>Warrington Wolves</name><abbreviation>WAR</abbreviation></competitor><competitor id="sr:competitor:4234"><name>St Helens</name><abbreviation>STH</abbreviation></competitor><competitor id="sr:competitor:4273"><name>Wakefield Trinity</name><abbreviation>WAK</abbreviation></competitor><competitor id="sr:competitor:4268"><name>Leeds Rhinos</name><abbreviation>LEE</abbreviation></competitor><competitor id="sr:competitor:4233"><name>Wigan Warriors</name><abbreviation>WGW</abbreviation></competitor><competitor id="sr:competitor:4269"><name>London Broncos</name><abbreviation>LON</abbreviation></competitor><competitor id="sr:competitor:4274"><name>Castleford Tigers</name><abbreviation>CAS</abbreviation></competitor><competitor id="sr:competitor:4272"><name>Bradford Bulls</name><abbreviation>BRA</abbreviation></competitor><competitor id="sr:competitor:4271"><name>Hull FC</name><abbreviation>HFC</abbreviation></competitor><competitor id="sr:competitor:4246"><name>Hull Kingston Rovers</name><abbreviation>HKR</abbreviation></competitor><competitor id="sr:competitor:4241"><name>Huddersfield Giants</name><abbreviation>HFG</abbreviation></competitor><competitor id="sr:competitor:7945"><name>Catalans Dragons</name><abbreviation>CAT</abbreviation></competitor></group></groups></stage></stages><competitors><competitor id="sr:competitor:4275"><name>Warrington Wolves</name><players/></competitor><competitor id="sr:competitor:4234"><name>St Helens</name><players/></competitor><competitor id="sr:competitor:4273"><name>Wakefield Trinity</name><players/></competitor><competitor id="sr:competitor:4268"><name>Leeds Rhinos</name><players/></competitor><competitor id="sr:competitor:4233"><name>Wigan Warriors</name><players/></competitor><competitor id="sr:competitor:4269"><name>London Broncos</name><players/></competitor><competitor id="sr:competitor:4274"><name>Castleford Tigers</name><players/></competitor><competitor id="sr:competitor:4272"><name>Bradford Bulls</name><players/></competitor><competitor id="sr:competitor:4271"><name>Hull FC</name><players/></competitor><competitor id="sr:competitor:4246"><name>Hull Kingston Rovers</name><players/></competitor><competitor id="sr:competitor:4241"><name>Huddersfield Giants</name><players/></competitor><competitor id="sr:competitor:7945"><name>Catalans Dragons</name><players/></competitor></competitors></season_data>
